import { Toaster } from "@/components/shadcn_ui/toaster";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";

const robotoMono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={"scroll-smooth"}>
			<head>
				<script
					src="https://challenges.cloudflare.com/turnstile/v0/api.js"
					async
					defer
				/>
			</head>
			<body className={robotoMono.className}>
				<main>{children}</main>
				<Toaster />
			</body>
		</html>
	);
}
